on:
  workflow_dispatch:
    deploy-destination:
        description: 'Environment'     
        required: true
        default: 'dev' 
        type: development
        options:
        - development
        - staging
        - production 

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: ../action
        with:
          who-to-greet: ${{ github.event.inputs.deploy-destination }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}